function data = ProjectMovieAll(workbookFile, sheetName, range)
%ÝMPORTFÝLE Import data from a spreadsheet
%   DATA = ÝMPORTFÝLE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   string array.
%
%   DATA = ÝMPORTFÝLE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = ÝMPORTFÝLE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.%
% Example:
%   MovieIDNameYearCreditsGenreString = ProjectMovieAll('ProjectMovieCredits.xlsx','Sheet1','A1:L241');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/12/29 14:36:23

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If no range is specified, read all data
if nargin <= 2 || isempty(range)
    range = '';
end

%% Import the data
[~, ~, data] = xlsread(workbookFile, sheetName, range);

data = string(data);
data(ismissing(data)) = '';
