function tableout = ProjectMovieIDNameYear(workbookFile,sheetName,startRow,endRow)
%ÝMPORTFÝLE Import data from a spreadsheet
%   DATA = ÝMPORTFÝLE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = ÝMPORTFÝLE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = ÝMPORTFÝLE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   ProjectHashtags = ProjectMovieIDNameYear('ProjectHashtags.xlsx','Sheet1',1,241);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/12/29 08:55:18

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 241;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:C%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:C%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
stringVectors = string(raw(:,2));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[1,3]);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.MovieID = data(:,1);
tableout.MovieName = stringVectors(:,1);
tableout.MovieYear = data(:,2);

